const words = [
    { question: "はじめまして", answer: "nice to see you" },
    { question: "わたし", answer: "I" },
    { question: "おねがいします", answer: "please" },
    { question: "にほんご", answer: "japanese" },
    { question: "がっこう", answer: "school" },
    { question: "がくせい", answer: "student" },
    { question: "から", answer: "from" },
    { question: "きました", answer: "came" },
    { question: "はい", answer: "yes" },
    { question: "いいえ", answer: "no" },
    { question: "そうです", answer: "that is correct" },
    { question: "おしごと（しごと）", answer: "work" },
    { question: "えいご", answer: "english" },
    { question: "きょうし", answer: "teacher" },
    { question: "も", answer: "too" },
    { question: "びょういん", answer: "hospital" },
    { question: "だいがく", answer: "university" },
    { question: "かいしゃいん", answer: "company employee" },
    { question: "けんしゅうせい", answer: "trainee" },
    { question: "りょこう", answer: "travel" },
    { question: "は", answer: "is" },
    { question: "の", answer: "of" },
    { question: "すみません", answer: "sorry" },
    { question: "もういちど", answer: "one more time" },
    { question: "えーと", answer: "well" },
    { question: "いま", answer: "now" },
    { question: "ほんと", answer: "really" },
];