const words = [
    { question: "にほんご（　）たのしいです\nJapanese is fun.", answer: ["は" ]},
    { question: "しんじゅく（　）いきます\nwill go to Shinjuku.", answer: ["に" ]},
    { question: "おかし（　）ありません\nsnack is not here.", answer: ["が" ]},
    { question: "ひがし（　）むかいます\nwill head to east", answer: ["へ" ]},
    { question: "あそび（　）きます\nwill come and play", answer: ["に" ]},
    { question: "かいもの（　）いきます\nwill go for shopping", answer: ["に" ]},
    { question: "ちち（　）あいます\nwill meet with father", answer: ["に" ]},
    { question: "いえ（　）でます\nwill go out from house", answer: ["を" ]},
    { question: "きょうかい（　）とおります\nwill path through the church", answer: ["を" ]},
    { question: "こども（　）おかしをかいます\nwill buy snack to child", answer: ["に" ]},
    { question: "した（　）さがります\nwill go down", answer: ["へ" ]},
    { question: "いす の となり（　）あります\n(it is) next to the chair", answer: ["に" ]},
    { question: "かばん の なか（　）いれます\nwill put into the bag", answer: ["に" ]},
    { question: "りょうり（　）にがてです\nnot good at cooking", answer: ["が" ]},
    { question: "あかいテーブル（　）あります\nThere is red table", answer: ["が" ]},
    { question: "かわ（　）およぐ\nswim at the river", answer: ["を" ]},
    { question: "ふく（　）きる\nひだり", answer: ["を" ]},
    { question: "がくせい（　）バスにのる\nstudent ride on the bus", answer: ["が" ]},
    { question: "かようび（　）2がつ3にちです\nTuesday is 3rd of Feb.", answer: ["は" ]},
    { question: "からだ（　）かゆい\nbody is itchy", answer: ["が" ]},
    { question: "ラーメン（　）すき\nl love Ramen", answer: ["が" ]},
    { question: "さとう（　）ほしい\nI want suger", answer: ["が" ]},
    { question: "さとう（　）ください\nPlease give me suger", answer: ["を" ]},
    { question: "あの かど（　）まがる\nturn at that corner", answer: ["を" ]},
    { question: "あさ十時（　）起きる\nget up at 10 o'clock", answer: ["に" ]},
    { question: "なごや（　）いく\ngo to Nagoya (not specific place)", answer: ["へ" ]},
    { question: "５時になごや（　）いく\ngo to Nagoya at 5 o'clock(specific)", answer: ["に" ]},
    { question: "はは（　）かいもの しています\n(Hey look!)Mother is doing shopping!", answer: ["が" ]},
    { question: "はは（　）かいもの しています\n(Someone asked you where she is)\nMother is went for shopping.", answer: ["は" ]},
    { question: "あに（　）きく\nask for my older brother", answer: ["に" ]},

];

