const words = [
    { question: "あたま", answer: "head" },
    { question: "あまい", answer: "sweet" },
    { question: "いえいえ", answer: "not at all" },
    { question: "いちご", answer: "strawberry" },
    { question: "いぬ", answer: "dog" },
    { question: "いみ", answer: "meaning" },
    { question: "うた", answer: "song" },
    { question: "うたいます", answer: "will sing" },
    { question: "おばあさん", answer: "old woman" },
    { question: "おんがく", answer: "music" },
    { question: "カツカレー", answer: "fried cutlet curry" },
    { question: "かんじ", answer: "chinese characters" },
    { question: "げつようび", answer: "Monday" },
    { question: "こたえ", answer: "answer" },
    { question: "サッカー", answer: "soccer" },
    { question: "じょうず（な）", answer: "excellent" },
    { question: "すき（な）", answer: "favored" },
    { question: "スポーツ", answer: "sports" },
    { question: "ぜんぜん（〜ない）", answer: "not at all" },
    { question: "だいすき（な）", answer: "favorite" },
    { question: "だめ（な）", answer: "not good" },
    { question: "だいたい", answer: "roughly" },
    { question: "たべもの", answer: "food" },
    { question: "ちち", answer: "father" },
    { question: "ちゅうごくご", answer: "Chinese" },
    { question: "チョコレート", answer: "chocolate" },
    { question: "つめたい", answer: "cold" },
    { question: "どうぶつ", answer: "animal" },
    { question: "とくに", answer: "in particular" },
    { question: "とけい", answer: "clock" },
    { question: "トマト", answer: "tomato" },
    { question: "ねこ", answer: "cat" },
    { question: "のみもの", answer: "beverage" },
    { question: "はなし", answer: "discussion" },
    { question: "ばんごう", answer: "number" },
    { question: "ピアノ", answer: "piano" },
    { question: "ビール", answer: "beer" },
    { question: "ぶちょう", answer: "manager" },
    { question: "フランスご", answer: "French" },
    { question: "へた（な）", answer: "poor" },
    { question: "ほし", answer: "star" },
    { question: "ほしい", answer: "want" },
    { question: "ポップス", answer: "pop" },
    { question: "もの", answer: "thing" },
    { question: "ルール", answer: "rule" },
    { question: "わかります", answer: "understand" },
];