const words = [
    { message: "Change following adjective word to the negative.",question: "いっしょ",meaning:  ["together" ], answer: ["いっしょじゃない","いっしょではない","いっしょじゃありません","いっしょではありません" ]},
    { message: "Change following adjective word to the negative.",question: "いや",meaning:  ["not likable","unpleasant" ], answer: ["いやじゃない","いやではない","いやじゃありません","いやではありません" ]},
    { message: "Change following adjective word to the negative.",question: "おおぜい",meaning:  ["many people" ], answer: ["おおぜいじゃない","おおぜいではない","おおぜいじゃありません","おおぜいではありません" ]},
    { message: "Change following adjective word to the negative.",question: "おなじ",meaning:  ["same" ], answer: ["おなじじゃない","おなじではない","おなじじゃありません","おなじではありません" ]},
    { message: "Change following adjective word to the negative.",question: "きらい",meaning:  ["dislike" ], answer: ["きらいじゃない","きらいではない","きらいじゃありません","きらいではありません" ]},
    { message: "Change following adjective word to the negative.",question: "きれい",meaning:  ["beautiful","clean" ], answer: ["きれいじゃない","きれいではない","きれいじゃありません","きれいではありません" ]},
    { message: "Change following adjective word to the negative.",question: "げんき",meaning:  ["vigor","health","vitality" ], answer: ["げんきじゃない","げんきではない","げんきじゃありません","げんきではありません" ]},
    { message: "Change following adjective word to the negative.",question: "しずか",meaning:  ["quiet" ], answer: ["しずかじゃない","しずかではない","しずかじゃありません","しずかではありません" ]},
    { message: "Change following adjective word to the negative.",question: "じょうず",meaning:  ["good at" ], answer: ["じょうずじゃない","じょうずではない","じょうずじゃありません","じょうずではありません" ]},
    { message: "Change following adjective word to the negative.",question: "じょうぶ",meaning:  ["strong","durable" ], answer: ["じょうぶじゃない","じょうぶではない","じょうぶじゃありません","じょうぶではありません" ]},
    { message: "Change following adjective word to the negative.",question: "だいじょうぶ",meaning:  ["ok","alright" ], answer: ["だいじょうぶじゃない","だいじょうぶではない","だいじょうぶじゃありません","だいじょうぶではありません" ]},
    { message: "Change following adjective word to the negative.",question: "だいすき",meaning:  ["love" ], answer: ["だいすきじゃない","だいすきではない","だいすきじゃありません","だいすきではありません" ]},
    { message: "Change following adjective word to the negative.",question: "たいせつ",meaning:  ["important" ], answer: ["たいせつじゃない","たいせつではない","たいせつじゃありません","たいせつではありません" ]},
    { message: "Change following adjective word to the negative.",question: "たいへん",meaning:  ["very","serious" ], answer: ["たいへんじゃない","たいへんではない","たいへんじゃありません","たいへんではありません" ]},
    { message: "Change following adjective word to the negative.",question: "にぎやか",meaning:  ["lively" ], answer: ["にぎやかじゃない","にぎやかではない","にぎやかじゃありません","にぎやかではありません" ]},
    { message: "Change following adjective word to the negative.",question: "ひま",meaning:  ["free time","leisure","boring" ], answer: ["ひまじゃない","ひまではない","ひまじゃありません","ひまではありません" ]},
    { message: "Change following adjective word to the negative.",question: "へた",meaning:  ["not good at" ], answer: ["へたじゃない","へたではない","へたじゃありません","へたではありません" ]},
    { message: "Change following adjective word to the negative.",question: "べんり",meaning:  ["convenient" ], answer: ["べんりじゃない","べんりではない","べんりじゃありません","べんりではありません" ]},
    { message: "Change following adjective word to the negative.",question: "まっすぐ",meaning:  ["straight ahead" ], answer: ["まっすぐじゃない","まっすぐではない","まっすぐじゃありません","まっすぐではありません" ]},
    { message: "Change following adjective word to the negative.",question: "りっぱ",meaning:  ["splendid" ], answer: ["りっぱじゃない","りっぱではない","りっぱじゃありません","りっぱではありません" ]},    
];

