const words = [
    { jp: "はじめまして", english: "nice to see you" },
    { jp: "わたし", english: "I" },
    { jp: "おねがいします", english: "please" },
    { jp: "にほんご", english: "japanese" },
    { jp: "がっこう", english: "school" },
    { jp: "がくせい", english: "student" },
    { jp: "から", english: "from" },
    { jp: "きました", english: "came" },
    { jp: "はい", english: "yes" },
    { jp: "いいえ", english: "no" },
    { jp: "そうです", english: "that is correct" },
    { jp: "おしごと（しごと）", english: "work" },
    { jp: "えいご", english: "english" },
    { jp: "きょうし", english: "teacher" },
    { jp: "も", english: "too" },
    { jp: "びょういん", english: "hospital" },
    { jp: "だいがく", english: "university" },
    { jp: "かいしゃいん", english: "company employee" },
    { jp: "けんしゅうせい", english: "trainee" },
    { jp: "りょこう", english: "travel" },
    { jp: "は", english: "is" },
    { jp: "の", english: "of" },
    { jp: "すみません", english: "sorry" },
    { jp: "もういちど", english: "one more time" },
    { jp: "えーと", english: "well" },
    { jp: "いま", english: "now" },
    { jp: "ほんと", english: "really" },
];