const words = [
    { question: "あまり", answer: ["not much" ]},
    { question: "いちばん", answer: ["best","no.1","most" ]},
    { question: "いつも", answer: ["always" ]},
    { question: "けっこう", answer: ["quite" ]},
    { question: "すぐに", answer: ["at once","soon" ]},
    { question: "すこし", answer: ["a little" ]},
    { question: "ぜんぶ", answer: ["all" ]},
    { question: "たいてい", answer: ["mostly"," usually" ]},
    { question: "たくさん", answer: ["many","much" ]},
    { question: "たぶん", answer: ["perhaps","probably","may be" ]},
    { question: "だんだん", answer: ["gradually" ]},
    { question: "ちょうど", answer: ["just" ]},
    { question: "どう", answer: ["how" ]},
    { question: "どうして", answer: ["why" ]},
    { question: "ときどき", answer: ["sometimes" ]},
    { question: "とても", answer: ["very" ]},
    { question: "はじめて", answer: ["first time" ]},
    { question: "はんぶん", answer: ["half" ]},
    { question: "ほんとうに", answer: ["really" ]},
    { question: "まいあさ", answer: ["every morning" ]},
    { question: "まいつき", answer: ["every month" ]},
    { question: "まいしゅう", answer: ["every week" ]},
    { question: "まいにち", answer: ["every day" ]},
    { question: "まいとし", answer: ["every year" ]},
    { question: "まいばん", answer: ["every evening" ]},
    { question: "また", answer: ["also","again" ]},
    { question: "まだ", answer: ["not yet" ]},
    { question: "もう (time)", answer: ["already","yet" ]},
    { question: "もう~(number)", answer: ["more" ]},
    { question: "もちろん", answer: ["of course" ]},
    { question: "もっと", answer: ["more" ]},
    { question: "よく", answer: ["often" ]},
];

