const words = [
    { question: "あさごはん", answer: "breakfast" },
    { question: "あたらしい", answer: "new" },
    { question: "ありがとうございます。", answer: "thank you very much" },
    { question: "アルバイト", answer: "part time job" },
    { question: "いいですね。", answer: "sounds good" },
    { question: "いいですよ。", answer: "ok" },
    { question: "いっしょに", answer: "together" },
    { question: "えいが", answer: "movie" },
    { question: "おはなみ", answer: "flower viewing" },
    { question: "かいます", answer: "will buy" },
    { question: "かいもの", answer: "purchase" },
    { question: "かきます", answer: "will draw" },
    { question: "カラオケ", answer: "karaoke" },
    { question: "きっぷ", answer: "ticket" },
    { question: "きのう", answer: "yesterday" },
    { question: "きょねん", answer: "last year" },
    { question: "９がつ", answer: "September" },
    { question: "ケーキ", answer: "cake" },
    { question: "けさ", answer: "this morning" },
    { question: "けっこうです。", answer: "that's fine" },
    { question: "コーヒー", answer: "coffee" },
    { question: "これから", answer: "after this" },
    { question: "ごろ", answer: "around" },
    { question: "さっき", answer: "minute ago" },
    { question: "します", answer: "will do" },
    { question: "じゅぎょう", answer: "class" },
    { question: "スキー", answer: "ski" },
    { question: "すこし", answer: "a little" },
    { question: "せんしゅう", answer: "last week" },
    { question: "そうじ", answer: "cleaning" },
    { question: "たべます", answer: "will eat" },
    { question: "たまご", answer: "egg" },
    { question: "だめ", answer: "no good" },
    { question: "ちょっと", answer: "a little" },
    { question: "つかいます", answer: "will use" },
    { question: "つくります", answer: "will make" },
    { question: "てがみ", answer: "letter" },
    { question: "テニス", answer: "tennis" },
    { question: "デパート", answer: "department store" },
    { question: "ときどき", answer: "sometimes" },
    { question: "とります", answer: "will take" },
    { question: "なつやすみ", answer: "summer holiday" },
    { question: "のみます", answer: "will drink" },
    { question: "はじめて", answer: "first time" },
    { question: "パン", answer: "bread" },
    { question: "ひ", answer: "day" },
    { question: "へえ", answer: "Huh" },
    { question: "へや", answer: "room" },
    { question: "みます", answer: "will watch" },
    { question: "メール", answer: "mail" },
    { question: "やすみ", answer: "holiday" },
    { question: "やすみます", answer: "will take a break" },
];