const words = [
    { question: "あう [to meet]", answer: "あいます" },
    { question: "あるく [to walk]", answer: "あるきます" },
    { question: "いく [to go]", answer: "いきます" },
    { question: "いる [to exist]", answer: "いります" },
    { question: "いれる [to insert, to put in]", answer: "いれます" },
    { question: "うたう [to sing]", answer: "うたいます" },
    { question: "おきる [to get up]", answer: "おきます" },
    { question: "おぼえる [to memorize]", answer: "おぼえます" },
    { question: "かう [to buy]", answer: "かいます" },
    { question: "かえす [to return(object)]", answer: "かえします" },
    { question: "かえる [to go back]", answer: "かえります" },
    { question: "きく [to hear, to listen, to ask]", answer: "ききます" },
    { question: "すむ [to live]", answer: "すみます" },
    { question: "する [to do]", answer: "します" },
    { question: "すわる [to sit]", answer: "すわります" },
    { question: "たべる [to eat]", answer: "たべます" },
    { question: "つかう [to use]", answer: "つかいます" },
    { question: "つくる [to make]", answer: "つくります" },
    { question: "とまる [to stop]", answer: "とまります" },
    { question: "ねる [to sleep]", answer: "ねます" },
    { question: "のむ [to drink]", answer: "のみます" },
    { question: "のる [to take, to ride]", answer: "のります" },
    { question: "はいる [to enter]", answer: "はいります" },
    { question: "はしる [to run]", answer: "はしります" },
    { question: "はたらく [to work]", answer: "はたらきます" },
    { question: "はなす [to talk, to speak, to tell]", answer: "はなします" },
    { question: "みる [to see, to watch]", answer: "みます" },
    { question: "もつ [to have, to own]", answer: "もちます" },
    { question: "やすむ [to rest]", answer: "やすみます" },
    { question: "よぶ [to call]", answer: "よびます" },
    { question: "よむ [to read]", answer: "よみます" },
    { question: "わかる [to know, to understand]", answer: "わかります" },

];