const words = [
    { question: "えはがき", answer: "picture postcard" },
    { question: "おかね", answer: "money" },
    { question: "おくります", answer: "will send" },
    { question: "おちゃ", answer: "tea" },
    { question: "おみやげ", answer: "present" },
    { question: "かぞく", answer: "family" },
    { question: "カフェ", answer: "cafe" },
    { question: "かります", answer: "will borrow" },
    { question: "かわいい", answer: "cute" },
    { question: "ききます", answer: "will ask" },
    { question: "こうちゃ", answer: "black tea" },
    { question: "コピー", answer: "copy" },
    { question: "しゅうまつ", answer: "weekend" },
    { question: "しゅくだい", answer: "homework" },
    { question: "スマホ", answer: "smartphone" },
    { question: "ぜんぜん", answer: "not at all" },
    { question: "そんなに", answer: "not much at all" },
    { question: "だします", answer: "will bring out" },
    { question: "でも", answer: "but" },
    { question: "どこか", answer: "somewhere" },
    { question: "ドラマ", answer: "drama" },
    { question: "なにか", answer: "something" },
    { question: "ニュース", answer: "news" },
    { question: "～にします", answer: "will have" },
    { question: "ねだん", answer: "price" },
    { question: "ネット", answer: "internet" },
    { question: "はがき", answer: "postcard" },
    { question: "パソコン", answer: "computer" },
    { question: "はなします", answer: "will talk" },
    { question: "はは", answer: "mother" },
    { question: "プレゼント", answer: "present" },
    { question: "へんじ", answer: "reply" },
    { question: "まだ", answer: "not yet" },
    { question: "もう", answer: "already" },
    { question: "アイスコーヒー", answer: "iced coffee" },
    { question: "あいます", answer: "will meet" },
    { question: "あつい", answer: "hot" },
    { question: "アプリ", answer: "app" },
    { question: "あまり", answer: "not really" },
    { question: "いもうと", answer: "little sister" },
    { question: "Aランチ", answer: "A lunch" },
    { question: "もうひとつ", answer: "one more" },
    { question: "もっていきます", answer: "will bring" },
    { question: "やっぱり", answer: "after all" },
    { question: "よく", answer: "often" },
    { question: "ラーメン", answer: "ramen" },
];