const words = [
    { message: "Change following adjective word to the NEGATIVE.",question: "あおい",meaning:  ["blue" ], answer: ["あおくない" ]},
    { message: "Change following adjective word to the PAST.",question: "あかい",meaning:  ["red" ], answer: ["あかかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "あかるい",meaning:  ["light","bright" ], answer: ["あかるくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "あたたかい",meaning:  ["warm" ], answer: ["あたたかくない" ]},
    { message: "Change following adjective word to the PAST.",question: "あたらしい",meaning:  ["new" ], answer: ["あたらしかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "あつい",meaning:  ["hot" ], answer: ["あつくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "あつい",meaning:  ["thick" ], answer: ["あつくない" ]},
    { message: "Change following adjective word to the PAST.",question: "あぶない",meaning:  ["dangerous" ], answer: ["あぶなかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "あまい",meaning:  ["sweet" ], answer: ["あまくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "いそがしい",meaning:  ["to be busy" ], answer: ["いそがしくない" ]},
    { message: "Change following adjective word to the PAST.",question: "いたい",meaning:  ["to be painful" ], answer: ["いたかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "いっしょ",meaning:  ["together" ], answer: ["いっしょじゃなかった","いっしょではなかった","いっしょじゃありませんでした","いっしょではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "いや",meaning:  ["not likable","unpleasant" ], answer: ["いやじゃない","いやではない","いやじゃありません","いやではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "うすい",meaning:  ["thin" ], answer: ["うすかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "おいしい",meaning:  ["tasty","delicious" ], answer: ["おいしくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "おおきい",meaning:  ["big" ], answer: ["おおきくない" ]},
    { message: "Change following adjective word to the PAST.",question: "おおぜい",meaning:  ["many people" ], answer: ["おおぜいだった","おおぜいでした","おおぜいじゃありません","おおぜいではありません" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "おそい",meaning:  ["late","slow" ], answer: ["おそくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "おなじ",meaning:  ["same" ], answer: ["おなじじゃない","おなじではない","おなじじゃありません","おなじではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "おもい",meaning:  ["heavy" ], answer: ["おもかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "おもしろい",meaning:  ["interesting","funny" ], answer: ["おもしろくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "からい",meaning:  ["hot","spicy" ], answer: ["からくない" ]},
    { message: "Change following adjective word to the PAST.",question: "かるい",meaning:  ["light","not heavy" ], answer: ["かるかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "かわいい",meaning:  ["cute","pretty" ], answer: ["かわいくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "きたない",meaning:  ["dirty" ], answer: ["きたなくない" ]},
    { message: "Change following adjective word to the PAST.",question: "きらい",meaning:  ["unpleasant","not likable" ], answer: ["きらいだった","きらいでした","きらいじゃありません","きらいではありません" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "きれい",meaning:  ["beautiful","clean" ], answer: ["きれいじゃなかった","きれいではなかった","きれいじゃありませんでした","きれいではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "くらい",meaning:  ["dark" ], answer: ["くらくない" ]},
    { message: "Change following adjective word to the PAST.",question: "くろい",meaning:  ["black" ], answer: ["くろかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "げんき",meaning:  ["vigor","health","vitality" ], answer: ["げんきじゃなかった","げんきではなかった","げんきじゃありませんでした","げんきではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "さむい",meaning:  ["cold" ], answer: ["さむくない" ]},
    { message: "Change following adjective word to the PAST.",question: "しずか",meaning:  ["quiet" ], answer: ["しずかだった","しずかでした","しずかじゃありません","しずかではありません" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "じょうず",meaning:  ["good at" ], answer: ["じょうずじゃなかった","じょうずではなかった","じょうずじゃありませんでした","じょうずではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "じょうぶ",meaning:  ["strong","durable" ], answer: ["じょうぶじゃない","じょうぶではない","じょうぶじゃありません","じょうぶではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "しろい",meaning:  ["white" ], answer: ["しろかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "すずしい",meaning:  ["cool" ], answer: ["すずしくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "せまい",meaning:  ["narrow" ], answer: ["せまくない" ]},
    { message: "Change following adjective word to the PAST.",question: "だいじょうぶ",meaning:  ["OK" ], answer: ["だいじょうぶだった","だいじょうぶでした","だいじょうぶじゃありません","だいじょうぶではありません" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "だいすき",meaning:  ["to be very fond of","love","very likable" ], answer: ["だいすきじゃなかった","だいすきではなかった","だいすきじゃありませんでした","だいすきではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "たいせつ",meaning:  ["very important" ], answer: ["たいせつじゃない","たいせつではない","たいせつじゃありません","たいせつではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "たいへん",meaning:  ["very","serious" ], answer: ["たいへんだった","たいへんでした","たいへんじゃありません","たいへんではありません" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "たかい",meaning:  ["high, expensive" ], answer: ["たかくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "たのしい",meaning:  ["pleasant","enjoyable" ], answer: ["たのしくない" ]},
    { message: "Change following adjective word to the PAST.",question: "ちいさい",meaning:  ["small" ], answer: ["ちいさかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "ちかい",meaning:  ["near","close" ], answer: ["ちかくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "つまらない",meaning:  ["uninteresting" ], answer: ["つまらなくない" ]},
    { message: "Change following adjective word to the PAST.",question: "つめたい",meaning:  ["cold" ], answer: ["つめたかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "つよい",meaning:  ["strong" ], answer: ["つよくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "とおい",meaning:  ["far" ], answer: ["とおくない" ]},
    { message: "Change following adjective word to the PAST.",question: "ながい",meaning:  ["long" ], answer: ["ながかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "にぎやか",meaning:  ["lively" ], answer: ["にぎやかじゃなかった","にぎやかではなかった","にぎやかじゃありませんでした","にぎやかではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "はやい",meaning:  ["fast","quick" ], answer: ["はやくない" ]},
    { message: "Change following adjective word to the PAST.",question: "ひくい",meaning:  ["low" ], answer: ["ひくかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "ひま",meaning:  ["free time","leisure" ], answer: ["ひまじゃなかった","ひまではなかった","ひまじゃありませんでした","ひまではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "ひろい",meaning:  ["wide","spacious" ], answer: ["ひろくない" ]},
    { message: "Change following adjective word to the PAST.",question: "ふとい",meaning:  ["thick","fat" ], answer: ["ふとかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "ふるい",meaning:  ["old" ], answer: ["ふるくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "へた",meaning:  ["not good at" ], answer: ["へたじゃない","へたではない","へたじゃありません","へたではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "べんり",meaning:  ["convenient" ], answer: ["べんりだった","べんりでした","べんりじゃありません","べんりではありません" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "ほしい",meaning:  ["to want" ], answer: ["ほしくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "ほそい",meaning:  ["thin","fine" ], answer: ["ほそくない" ]},
    { message: "Change following adjective word to the PAST.",question: "まずい",meaning:  ["bad tasting" ], answer: ["まずかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "まっすぐ",meaning:  ["straight ahead" ], answer: ["まっすぐじゃなかった","まっすぐではなかった","まっすぐじゃありませんでした","まっすぐではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "まるい",meaning:  ["round" ], answer: ["まるくない" ]},
    { message: "Change following adjective word to the PAST.",question: "みじかい",meaning:  ["short" ], answer: ["みじかかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "むずかしい",meaning:  ["difficult" ], answer: ["むずかしくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "やさしい",meaning:  ["gentle" ], answer: ["やさしくない" ]},
    { message: "Change following adjective word to the PAST.",question: "やすい",meaning:  ["cheap","inexpensive" ], answer: ["やすかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "よい",meaning:  ["good" ], answer: ["よくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "りっぱ",meaning:  ["splendid" ], answer: ["りっぱじゃない","りっぱではない","りっぱじゃありません","りっぱではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "わかい",meaning:  ["young" ], answer: ["わかかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "わるい",meaning:  ["bad" ], answer: ["わるくなかった" ]}, 
];

