const words = [
    { question: "いき／ゆき", answer: "bound for" },
    { question: "1じかん（いちじかん）", answer: "1hour" },
    { question: "うみ", answer: "ocean" },
    { question: "おいしい", answer: "delicious" },
    { question: "おかし", answer: "snack" },
    { question: "おてら", answer: "temple" },
    { question: "かかります", answer: "takes" },
    { question: "くらい", answer: "about" },
    { question: "くるま", answer: "car" },
    { question: "けっこう", answer: "rather" },
    { question: "こうえん", answer: "park" },
    { question: "じかん", answer: "time" },
    { question: "しずか（な）", answer: "quiet" },
    { question: "しんかんせん", answer: "bullet train" },
    { question: "それから", answer: "after that" },
    { question: "どうやって", answer: "how" },
    { question: "ところ", answer: "place" },
    { question: "とても", answer: "extremely" },
    { question: "とまります", answer: "will stay at" },
    { question: "どれ", answer: "which" },
    { question: "どれくらい", answer: "how much" },
    { question: "なんばん", answer: "what number" },
    { question: "なんばんせん", answer: "which track number" },
    { question: "なんぷん", answer: "how many minutes" },
    { question: "にぎやか（な）", answer: "lively" },
    { question: "のりば", answer: "station" },
    { question: "のります", answer: "will get on" },
    { question: "はやい", answer: "quick" },
    { question: "ひとり", answer: "alone" },
    { question: "ひる", answer: "daytime" },
    { question: "ひま（な）", answer: "unoccupied" },
    { question: "べんり（な）", answer: "convenient" },
    { question: "まえ", answer: "front" },
    { question: "ゆうめい（な）", answer: "famous" },
    { question: "よる", answer: "night" },
];