const words = [
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "いっしょ", answer: ["[Meaning : together]","いっしょじゃない","いっしょではない","いっしょじゃありません","いっしょではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "いや", answer: ["[Meaning : not likable, unpleasant]","いやじゃない","いやではない","いやじゃありません","いやではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "おおぜい", answer: ["[Meaning : many people]","おおぜいじゃない","おおぜいではない","おおぜいじゃありません","おおぜいではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "おなじ", answer: ["[Meaning : same]","おなじじゃない","おなじではない","おなじじゃありません","おなじではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "きらい", answer: ["[Meaning : unpleasant, not likable]","きらいじゃない","きらいではない","きらいじゃありません","きらいではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "きれい", answer: ["[Meaning : beautiful, clean]","きれいじゃない","きれいではない","きれいじゃありません","きれいではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "げんき", answer: ["[Meaning : vigor, health, vitality]","げんきじゃない","げんきではない","げんきじゃありません","げんきではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "しずか", answer: ["[Meaning : quiet]","しずかじゃない","しずかではない","しずかじゃありません","しずかではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "じょうず", answer: ["[Meaning : to be good at something]","じょうずじゃない","じょうずではない","じょうずじゃありません","じょうずではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "じょうぶ", answer: ["[Meaning : to be strong, durable]","じょうぶじゃない","じょうぶではない","じょうぶじゃありません","じょうぶではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "だいじょうぶ", answer: ["[Meaning : OK]","だいじょうぶじゃない","だいじょうぶではない","だいじょうぶじゃありません","だいじょうぶではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "だいすき", answer: ["[Meaning : to be very fond of]","だいすきじゃない","だいすきではない","だいすきじゃありません","だいすきではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "たいせつ", answer: ["[Meaning : very important]","たいせつじゃない","たいせつではない","たいせつじゃありません","たいせつではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "たいへん", answer: ["[Meaning : very, serious]","たいへんじゃない","たいへんではない","たいへんじゃありません","たいへんではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "にぎやか", answer: ["[Meaning : lively]","にぎやかじゃない","にぎやかではない","にぎやかじゃありません","にぎやかではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "ひま", answer: ["[Meaning : free time, leisure]","ひまじゃない","ひまではない","ひまじゃありません","ひまではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "へた", answer: ["[Meaning : not good at something]","へたじゃない","へたではない","へたじゃありません","へたではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "べんり", answer: ["[Meaning : convenient]","べんりじゃない","べんりではない","べんりじゃありません","べんりではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "まっすぐ", answer: ["[Meaning : straight ahead]","まっすぐじゃない","まっすぐではない","まっすぐじゃありません","まっすぐではありません" ]},
    { message: "Change following adjective word to the negative. Type by Hiragana!",question: "りっぱ", answer: ["[Meaning : splendid]","りっぱじゃない","りっぱではない","りっぱじゃありません","りっぱではありません" ]},
];