const words = [
    { question: "えき", answer: "station" },
    { question: "おちゃ", answer: "tea" },
    { question: "おとうさん", answer: "father" },
    { question: "がいこくじん", answer: "foreigner" },
    { question: "がくせい", answer: "student" },
    { question: "かのじょ", answer: "she" },
    { question: "かれ", answer: "he" },
    { question: "きのう", answer: "yesterday" },
    { question: "こうえん", answer: "park" },
    { question: "こうばん", answer: "police station" },
    { question: "これ", answer: "this" },
    { question: "あれ", answer: "that" },
    { question: "こんしゅう", answer: "this week" },
    { question: "しごと", answer: "work" },
    { question: "それ", answer: "that" },
    { question: "たんじょうび", answer: "birthday" },
    { question: "とけい", answer: "clock" },
    { question: "ねこ", answer: "cat" },
    { question: "はい", answer: "yes" },
    { question: "はな", answer: "flower" },
    { question: "びょういん", answer: "hospital" },
    { question: "やすみ", answer: "holiday" },
    { question: "らいしゅう", answer: "next week" },
    { question: "りょこう", answer: "travel" },
    { question: "わたし", answer: "I" },
];