const words = [
    { question: "日", answer: ["jitsu","nichi","hi","bi","ka" ]},
    { question: "一", answer: ["ichi","hito" ]},
    { question: "国", answer: ["kuni","koku" ]},
    { question: "人", answer: ["jin","nin","hito" ]},
    { question: "年", answer: ["nen","toshi" ]},
    { question: "大", answer: ["dai","tai","oo" ]},
    { question: "十", answer: ["juu","too","to" ]},
    { question: "ニ", answer: ["ni","futa" ]},
    { question: "本", answer: ["hon","moto" ]},
    { question: "中", answer: ["naka","chuu","jyuu" ]},
    { question: "長", answer: ["chou","naga" ]},
    { question: "出", answer: ["de","shutsu" ]},
    { question: "三", answer: ["san","mi" ]},
    { question: "時", answer: ["toki","ji","doki" ]},
    { question: "行", answer: ["kou","i","yu","gyou" ]},
    { question: "見", answer: ["mi","ken" ]},
    { question: "月", answer: ["getsu","gatsu","tsuki" ]},
    { question: "分", answer: ["fun","bun","wa" ]},
    { question: "後", answer: ["go","ato","kou","ushi" ]},
    { question: "前", answer: ["mae","zen" ]},
    { question: "火", answer: ["ka","hi" ]},
    { question: "水", answer: ["sui","mizu" ]},
    { question: "木", answer: ["moku","ki" ]},
    { question: "金", answer: ["kin","kane" ]},
    { question: "土", answer: ["do","tsuchi" ]},
];