const words = [
    { question: "あさ", answer: "morning" },
    { question: "アパート", answer: "apartment" },
    { question: "あるく", answer: "to walk" },
    { question: "いえ", answer: "house" },
    { question: "いま", answer: "now" },
    { question: "いりぐち", answer: "entrance" },
    { question: "エレベータ", answer: "elevator" },
    { question: "おてあらい", answer: "toilet" },
    { question: "おととい", answer: "the day before yesterday" },
    { question: "おととし", answer: "the year before last" },
    { question: "かいだん", answer: "stairs" },
    { question: "かえる", answer: "to return home" },
    { question: "かど", answer: "corner" },
    { question: "かようび", answer: "Tuesday" },
    { question: "きっさてん", answer: "coffee shop" },
    { question: "きょう", answer: "today" },
    { question: "きょねん", answer: "last year" },
    { question: "ぎんこう", answer: "bank" },
    { question: "きんようび", answer: "Friday" },
    { question: "くに", answer: "country" },
    { question: "クラス", answer: "class" },
    { question: "けさ", answer: "this morning" },
    { question: "げつようび", answer: "Monday" },
    { question: "げんかん", answer: "entrance" },
    { question: "ごご", answer: "afternoon" },
    { question: "ごぜん", answer: "am" },
    { question: "ことし", answer: "this year" },
    { question: "こんげつ", answer: "this month" },
    { question: "こんばん", answer: "this evening" },
    { question: "さらいねん", answer: "the year after next year" },
    { question: "じかん", answer: "time" },
    { question: "しょくどう", answer: "canteen" },
    { question: "すいようび", answer: "Wednesday" },
    { question: "すわる", answer: "to sit" },
    { question: "せんげつ", answer: "last month" },
    { question: "せんしゅう", answer: "last week" },
    { question: "そと", answer: "outside" },
    { question: "たいしかん", answer: "embassy" },
    { question: "だいどころ", answer: "kitchen" },
    { question: "たてもの", answer: "building" },
    { question: "たべる", answer: "to eat" },
    { question: "つくる", answer: "to make" },
    { question: "でぐち", answer: "exit" },
    { question: "デパート", answer: "department store" },
    { question: "ところ", answer: "place" },
    { question: "どようび", answer: "Saturday" },
    { question: "なつやすみ", answer: "summer vacation" },
    { question: "にちようび", answer: "Sunday" },
    { question: "にわ", answer: "garden" },
    { question: "ねる", answer: "to sleep" },
    { question: "はし", answer: "bridge" },
    { question: "はしる", answer: "to run" },
    { question: "はたらく", answer: "to work" },
    { question: "はなす", answer: "to talk" },
    { question: "ひる", answer: "noon" },
    { question: "へや", answer: "room" },
    { question: "ホテル", answer: "hotel" },
    { question: "まち", answer: "city, town" },
    { question: "もくようび", answer: "Thursday" },
    { question: "もつ", answer: "to carry" },
    { question: "よる", answer: "night" },
    { question: "らいげつ", answer: "next month" },
    { question: "らいねん", answer: "next year" },
    { question: "レストラン", answer: "restaurant" },
];