const words = [
    { question: "あたたかい", answer: "warm" },
    { question: "あぶない", answer: "dangerous" },
    { question: "あめ", answer: "rain" },
    { question: "あるきます", answer: "will walk" },
    { question: "いたい", answer: "painful" },
    { question: "おもしろい", answer: "interesting" },
    { question: "おわります", answer: "will end" },
    { question: "からい", answer: "spicy" },
    { question: "かんたん（な）", answer: "easy" },
    { question: "きらい（な）", answer: "disliked" },
    { question: "きれい（な）", answer: "beautiful" },
    { question: "げんき（な）", answer: "fine" },
    { question: "このまえ", answer: "the other day" },
    { question: "さむい", answer: "cold" },
    { question: "しんせつ（な）", answer: "kind" },
    { question: "すぐ", answer: "immediately" },
    { question: "すごく", answer: "incredibly" },
    { question: "たいへん（な）", answer: "tough" },
    { question: "たかい", answer: "high" },
    { question: "たのしい", answer: "fun" },
    { question: "てんちょう", answer: "manager" },
    { question: "ひろい", answer: "broad" },
    { question: "ふべん（な）", answer: "inconvenient" },
    { question: "ふるい", answer: "old" },
    { question: "まあまあ", answer: "okay" },
    { question: "まち", answer: "city" },
    { question: "むずかしい", answer: "difficult" },
    { question: "よろしい", answer: "good" },
];