const words = [
    { question: "大", answer: ["dai","tai","oo" ]},
    { question: "上", answer: ["jyou","ue","nobo","kami","a" ]},
    { question: "入", answer: ["nyuu","hai","i","iri" ]},
    { question: "下", answer: ["ka","ge","shita","shimo","sa" ]},
    { question: "小", answer: ["shou","chii","ko","o" ]},
    { question: "山", answer: ["san","yama" ]},
    { question: "女", answer: ["jyo","nyo","onna","me" ]},
    { question: "百", answer: ["hyaku","byaku","momo" ]},
    { question: "川", answer: ["kawa","sen","gawa" ]},
    { question: "千", answer: ["sen","chi" ]},
    { question: "男", answer: ["dan","nan","otoko","o" ]},
    { question: "万", answer: ["man","ban","yorozu" ]},
    { question: "天", answer: ["ten","ama" ]},
    { question: "休", answer: ["kyuu","yasumi" ]},
    { question: "雨", answer: ["u","ame","ama" ]},
];