const words = [
    { question: "あさ", answer: "morning" },
    { question: "あさって", answer: "the day after tomorrow" },
    { question: "あした", answer: "tomorrow" },
    { question: "いえ", answer: "house" },
    { question: "いきます", answer: "will go" },
    { question: "いそがしい", answer: "busy" },
    { question: "いつ", answer: "when" },
    { question: "いつも", answer: "always" },
    { question: "います", answer: "is there" },
    { question: "えき", answer: "station" },
    { question: "おきます", answer: "will wake up" },
    { question: "おともだち", answer: "friend" },
    { question: "おまつり", answer: "festival" },
    { question: "おやすみ", answer: "break" },
    { question: "かいぎ", answer: "meeting" },
    { question: "かいしゃ", answer: "company" },
    { question: "かえります", answer: "will go home" },
    { question: "かようび", answer: "tuesday" },
    { question: "きょう", answer: "today" },
    { question: "きをつけて。", answer: "be careful" },
    { question: "くうこう", answer: "airport" },
    { question: "ごご", answer: "pm" },
    { question: "ごぜん", answer: "am" },
    { question: "こんげつ", answer: "this month" },
    { question: "こんしゅう", answer: "this week" },
    { question: "～じ", answer: "hour" },
    { question: "しあい", answer: "match" },
    { question: "しがつ", answer: "April" },
    { question: "しちがつ", answer: "July" },
    { question: "じゅうよっか", answer: "14th" },
    { question: "じゅうはちにち", answer: "18th" },
    { question: "ぜひ。", answer: "by all means" },
    { question: "ソファー", answer: "sofa" },
    { question: "タクシー", answer: "taxi" },
    { question: "たんじょうび", answer: "birthday" },
    { question: "ちょうど", answer: "exactly" },
    { question: "つぎ", answer: "next" },
    { question: "つきます", answer: "will arrive" },
    { question: "でかけます", answer: "will go out" },
    { question: "テスト", answer: "test" },
    { question: "でんしゃ", answer: "train" },
    { question: "とうきょう", answer: "Tokyo" },
    { question: "としょかん", answer: "library" },
    { question: "どようび", answer: "saturday" },
    { question: "なんじ", answer: "what time" },
    { question: "なんぷん", answer: "what minutes" },
    { question: "にちようび", answer: "sunday" },
    { question: "ねます", answer: "will sleep" },
    { question: "パーティー", answer: "party" },
    { question: "はじまります", answer: "will begin" },
    { question: "はたらきます", answer: "will work" },
    { question: "はちがつ", answer: "August" },
    { question: "はやい", answer: "early" },
    { question: "はん", answer: "half" },
    { question: "ひこうき", answer: "airplane" },
    { question: "びじゅつかん", answer: "art museum" },
    { question: "ふん", answer: "minutes" },
    { question: "べんきょうします", answer: "will study" },
    { question: "ほっかいどう", answer: "hokkaido" },
    { question: "まいあさ", answer: "every morning" },
    { question: "まいにち", answer: "every day" },
    { question: "みっか", answer: "third" },
    { question: "みんな", answer: "everyone" },
    { question: "もうすぐ", answer: "soon" },
    { question: "もくようび", answer: "thursday" },
    { question: "ゆうびんきょく", answer: "post office" },
    { question: "らいげつ", answer: "next month" },
    { question: "らいしゅう", answer: "next week" },
];