const words = [
    { question: "ください", answer: "give me" },
    { question: "これ", answer: "this" },
    { question: "あれ", answer: "that" },
    { question: "それ", answer: "that" },
    { question: "この", answer: "this" },
    { question: "あの", answer: "that" },
    { question: "その", answer: "that" },
    { question: "なに", answer: "what" },
    { question: "だれ", answer: "who" },
    { question: "どれ", answer: "which" },
    { question: "なに", answer: "what" },
    { question: "だれ", answer: "whose" },
    { question: "どれ", answer: "which" },
    { question: "おねがいします", answer: "please" },
    { question: "なんですか？", answer: "what is" },
    { question: "え", answer: "picture" },
    { question: "はな", answer: "flower" },
    { question: "さくら", answer: "cherry blossom" },
    { question: "ちゅうもん", answer: "order" },
    { question: "とうふ", answer: "soybean curd" },
    { question: "りょうり", answer: "cooking" },
    { question: "しゃしん", answer: "photo" },
    { question: "ひと", answer: "person" },
    { question: "おみせ", answer: "shop" },
    { question: "せんせい", answer: "teacher" },
    { question: "おんな", answer: "woman" },
    { question: "おさら", answer: "dish" },
    { question: "おはし", answer: "chop stick" },
    { question: "かさ", answer: "umbrella" },
    { question: "じてんしゃ", answer: "bicycle" },
    { question: "じしょ", answer: "dictionary" },
    { question: "かばん", answer: "bag" },
    { question: "ともだち", answer: "friend" },
    { question: "だいがく", answer: "university" },
    { question: "しゃちょう", answer: "president" },
    { question: "おさけ", answer: "alcohol" },
    { question: "ほん", answer: "book" },
    { question: "ぎゅうにく", answer: "beef meat" },
    { question: "やさい", answer: "vegetable" },
    { question: "みそしる", answer: "miso soup" },
];