const words = [
    { question: "あく", answer: "open " },
    { question: "あける", answer: "to open" },
    { question: "あげる", answer: "to give" },
    { question: "あそぶ", answer: "to play" },
    { question: "あびる", answer: "to take a shower" },
    { question: "あらう", answer: "to wash" },
    { question: "ある", answer: "to exist" },
    { question: "いう", answer: "to say" },
    { question: "いる", answer: "to be need" },
    { question: "うまれる", answer: "to be born" },
    { question: "うる", answer: "to sell" },
    { question: "おく", answer: "to place" },
    { question: "おくる", answer: "to send" },
    { question: "おす", answer: "to push" },
    { question: "およぐ", answer: "to swim" },
    { question: "おりる", answer: "to get off" },
    { question: "おわる", answer: "to end" },
    { question: "かかる", answer: "to take time or money" },
    { question: "かく", answer: "to write" },
    { question: "かける", answer: "to wear" },
    { question: "かける", answer: "to make a phone call" },
    { question: "かす", answer: "to lend" },
    { question: "かぶる", answer: "to put on a hat" },
    { question: "かりる", answer: "to borrow" },
    { question: "〜がります", answer: "3rd person wants to" },
    { question: "きえる", answer: "to vanish" },
    { question: "きる", answer: "to cut" },
    { question: "きる", answer: "to wear" },
    { question: "くる", answer: "to come" },
    { question: "けす", answer: "to turn off" },
    { question: "こたえる", answer: "to answer" },
    { question: "こまる", answer: "to be in trouble" },
    { question: "さく", answer: "to blossom" },
    { question: "さす", answer: "to open an umbrella" },
    { question: "しぬ", answer: "to die, to pas away" },
    { question: "しまる", answer: "to close" },
    { question: "しめる", answer: "to close" },
    { question: "しめる", answer: "to fasten" },
    { question: "しる", answer: "to know" },
    { question: "すう", answer: "to breathe in" },
    { question: "すき", answer: "to like" },
    { question: "だす", answer: "to take out" },
    { question: "たつ", answer: "to stand" },
    { question: "たのむ", answer: "to ask" },
    { question: "つかれる", answer: "to get tired" },
    { question: "つく", answer: "to arrive" },
    { question: "つける", answer: "to turn on" },
    { question: "つとめる", answer: "to work for someone" },
    { question: "でかける", answer: "to go out" },
    { question: "できる", answer: "can" },
    { question: "でます", answer: "to leave" },
    { question: "とぶ", answer: "to fly" },
    { question: "とる", answer: "to take" },
    { question: "とる", answer: "to take a photo" },
    { question: "なく", answer: "to sing" },
    { question: "ならう", answer: "to learn" },
    { question: "ならぶ", answer: "to form a line" },
    { question: "ならべる", answer: "to line up" },
    { question: "なる", answer: "to become" },
    { question: "ぬぐ", answer: "to take off clothes" },
    { question: "のぼる", answer: "to climb up" },
    { question: "はく", answer: "to put on shoes" },
    { question: "はじまる", answer: "to begin" },
    { question: "はやい", answer: "early" },
    { question: "はる", answer: "to put something on, to stick" },
    { question: "はれる", answer: "to clear up" },
    { question: "ひく", answer: "to pull" },
    { question: "ひく", answer: "to play instrument" },
    { question: "ふく", answer: "to blow (wind)" },
    { question: "ふる", answer: "to fall rain or snow" },
    { question: "まがる", answer: "to turn" },
    { question: "まつ", answer: "to wait" },
    { question: "みがく", answer: "to brush" },
    { question: "みせる", answer: "to show" },
    { question: "やる", answer: "to do" },
    { question: "わすれる", answer: "to forget" },
    { question: "わたす", answer: "to hand over" },
    { question: "わたる", answer: "to cross" },
];