const words = [
    { question: "あいだ", answer: "between" },
    { question: "いそぎます", answer: "will hurry" },
    { question: "うえ", answer: "above" },
    { question: "エアコン", answer: "air conditioner" },
    { question: "えきまえ", answer: "in front of the station" },
    { question: "おまわりさん", answer: "police officer" },
    { question: "おんなのこ", answer: "girl" },
    { question: "かいぎ", answer: "meeting" },
    { question: "カフェ", answer: "cafe" },
    { question: "き", answer: "tree" },
    { question: "きっと", answer: "maybe" },
    { question: "げんかん", answer: "entrance" },
    { question: "こうばん", answer: "police station" },
    { question: "こまかい", answer: "small" },
    { question: "ごめんなさい", answer: "I'm sorry" },
    { question: "コンビニ", answer: "convenience store" },
    { question: "～さつ", answer: "volumes" },
    { question: "した", answer: "below" },
    { question: "しつもん", answer: "question" },
    { question: "だいじょうぶですか", answer: "all right?" },
    { question: "たくさん", answer: "many" },
    { question: "ちかく", answer: "nearby" },
    { question: "チケット", answer: "ticket" },
    { question: "テニスコート", answer: "tennis court" },
    { question: "ドリル", answer: "workbook" },
    { question: "なか", answer: "inside" },
    { question: "はいります", answer: "will enter" },
    { question: "バスてい", answer: "bus stop" },
    { question: "はなや", answer: "flower shop" },
    { question: "ポスト", answer: "post" },
    { question: "みなと", answer: "harbor" },
    { question: "ようじ", answer: "affairs" },
];