const words = [
    { question: "～は、どこですか？", answer: "where is" },
    { question: "ここ", answer: "here" },
    { question: "そこ", answer: "there" },
    { question: "あそこ", answer: "over there" },
    { question: "こちら", answer: "here" },
    { question: "そちら", answer: "there" },
    { question: "あちら", answer: "over there" },
    { question: "～かい", answer: "floor" },
    { question: "～は、いくらですか？", answer: "how much" },
    { question: "～は、どうですか？", answer: "how is" },
    { question: "くつ", answer: "shoes" },
    { question: "うりば", answer: "sales floor" },
    { question: "えん", answer: "yen" },
    { question: "いいですね", answer: "it's good" },
    { question: "あか", answer: "red" },
    { question: "あかい", answer: "red colored" },
    { question: "ネクタイ", answer: "necktie" },
    { question: "いかがですか？", answer: "how is it" },
    { question: "ちょっと", answer: "a little" },
    { question: "おもい", answer: "heavy" },
    { question: "では", answer: "then" },
    { question: "かるい", answer: "light" },
    { question: "ほか", answer: "other" },
    { question: "いろ", answer: "color" },
    { question: "～も", answer: "too" },
    { question: "ありますか？", answer: "is there" },
    { question: "くろ", answer: "black" },
    { question: "しろ", answer: "white" },
    { question: "あお", answer: "blue" },
    { question: "ケチャップ", answer: "ketchup" },
    { question: "たな", answer: "shelf" },
    { question: "わかりました", answer: "understood" },
    { question: "どうも", answer: "thank you" },
    { question: "トイレ", answer: "toilet" },
    { question: "きょうしつ", answer: "classroom" },
    { question: "いりぐち", answer: "entrance" },
    { question: "ほん", answer: "book" },
    { question: "レジ", answer: "cash register" },
    { question: "うけつけ", answer: "reception" },
    { question: "どちら", answer: "which direction" },
    { question: "すみません", answer: "excuse me" },
    { question: "たかい", answer: "expensive" },
    { question: "やすい", answer: "cheap" },
    { question: "みじかい", answer: "short" },
    { question: "ながい", answer: "long" },
    { question: "ちいさい", answer: "small" },
    { question: "おおきい", answer: "big" },
    { question: "もうすこし", answer: "little more" },
    { question: "ふとい", answer: "thick" },
    { question: "ほそい", answer: "thin" },
    { question: "なんかい", answer: "which floor" },
    { question: "ちか", answer: "underground" },
    { question: "ぎんこう", answer: "bank" },
    { question: "でんわ", answer: "phone" },
    { question: "えいがかん", answer: "movie theater" },
    { question: "フロント", answer: "front desk" },
    { question: "くだもの", answer: "fruit" },
    { question: "かぎ", answer: "key" },
    { question: "ごみばこ", answer: "trash can" },
    { question: "ちかてつ", answer: "subway" },
    { question: "ちず", answer: "map" },
    { question: "ほんや", answer: "bookstore" },
    { question: "かばん", answer: "bag" },
    { question: "じてんしゃ", answer: "bicycle" },
    { question: "こどもふく", answer: "child clothes" },
    { question: "あかちゃん", answer: "baby" },
    { question: "ふく", answer: "clothes" },
];