const words = [
    { question: "にほんご（　）たのしいですn/Japanese is fun.", answer: ["は" ]},
    { question: "しんじゅく（　）いきますn/will go to Shinjuku.", answer: ["に" ]},
    { question: "おかし（　）ありませんn/snack is not here.", answer: ["が" ]},
    { question: "ひがし（　）むかいますn/will head to east", answer: ["へ" ]},
    { question: "あそび（　）きますn/will come and play", answer: ["に" ]},
    { question: "かいもの（　）いきますn/will go for shopping", answer: ["に" ]},
    { question: "ちち（　）あいますn/will meet with father", answer: ["に" ]},
    { question: "いえ（　）でますn/will go out from house", answer: ["を" ]},
    { question: "きょうかい（　）とおりますn/will path through the church", answer: ["を" ]},
    { question: "こども（　）おかしをかいますn/will buy snack to child", answer: ["に" ]},
    { question: "した（　）さがりますn/will go down", answer: ["へ" ]},
    { question: "いす の となり（　）ありますn/(it is) next to the chair", answer: ["に" ]},
    { question: "かばん の なか（　）いれますn/will put into the bag", answer: ["に" ]},
    { question: "りょうり（）にがてですn/not good at cooking", answer: ["は" ]},
    { question: "あかいテーブル（　）ありますn/There is red table", answer: ["が" ]},
    { question: "かわ（　）およぐn/swim at the river", answer: ["を" ]},
    { question: "ふく（　）きるn/ひだり", answer: ["を" ]},
    { question: "がくせい（　）バスにのるn/student ride on the bus", answer: ["が" ]},
    { question: "かようび（　）2がつ3にちですn/Tuesday is 3rd of Feb.", answer: ["は" ]},
    { question: "からだ（　）かゆいn/body is itchy", answer: ["が" ]},
    { question: "ラーメン（　）すきn/l love Ramen", answer: ["が" ]},
    { question: "さとう（　）ほしいn/I want suger", answer: ["が" ]},
    { question: "さとう（　）くださいn/Please give me suger", answer: ["を" ]},
    { question: "あの かど（　）まがるn/turn at that corner", answer: ["を" ]},
    { question: "あさ十時（　）起きるn/get up at 10 o'clock", answer: ["に" ]},
    { question: "なごや（　）いくn/go to Nagoya (not specific place)", answer: ["へ" ]},
    { question: "５時になごや（　）いくn/go to Nagoya at 5 o'clock(specific)", answer: ["に" ]},
    { question: "はは（　）かいもの していますn/(Hey look!)Mother is doing shopping!", answer: ["が" ]},
    { question: "はは（　）かいもの していますn/(Someone asked you where she is)n/Mother is went for shopping.", answer: ["は" ]},
    { question: "あに（　）きくn/ask for my older brother", answer: ["に" ]},

];

