const words = [
    { question: "後", answer: ["go" ]},
    { question: "前", answer: ["zen" ]},
    { question: "上", answer: ["jou","ue","kami","a","nobo" ]},
    { question: "子", answer: ["shi","ko" ]},
    { question: "下", answer: ["ka","ge","shita","shimo","sa" ]},
    { question: "書", answer: ["sho","kaku" ]},
    { question: "半", answer: ["han","naka" ]},
    { question: "何", answer: ["nani","kaku","nann" ]},
    { question: "毎", answer: ["mai","goto" ]},
    { question: "母", answer: ["bo","haha","kaa" ]},
    { question: "右", answer: ["migi","u" ]},
    { question: "友", answer: ["yuu","tomo" ]},
    { question: "左", answer: ["sa","hidari" ]},
    { question: "父", answer: ["fu","chichi","tou" ]},
    { question: "近", answer: ["kinn","chika" ]},
    { question: "中", answer: ["naka","chuu" ]},
    { question: "外", answer: ["soto","gai","hazu" ]},
    { question: "横", answer: ["yoko","ou" ]},
];