const words = [
    { question: "わたし　は　がくせい　です", answer: "I am student" },
    { question: "かのじょ　は　いもうと　です", answer: "She is sister" },
    { question: "かれ　は　あに　ですか？", answer: "Is he brother?" },
    { question: "おとうさん　は　がいこくじん　ですか？", answer: "Is your father a foreigner?" },
    { question: "やまだ　さん　は　かいしゃいん　です", answer: "Mr Yamada is company employee" },
    { question: "あした　は　やすみ　ではありません", answer: "Tomorrow is not a holiday?" },
    { question: "いいえ, らいげつ　は　なつやすみ　ではありません", answer: "No, Next month is not summer holiday" },
    { question: "はい, こんしゅう　は　たんじょうび　です", answer: "Yes, this week is birthday" },
    { question: "あさっては　しごと　ですか？", answer: "Do you have work the day after tomorrow?" },
    { question: "らいしゅう　は　りょこう　ですか？", answer: "Are you going on a trip for next week?" },
    { question: "らいねん　は　びょういん　です", answer: "Are you going on a trip for next week?" },
    { question: "それ　は　おちゃ　ですか？", answer: "Is that tea?" },
    { question: "それ　は　ねこ　ですか？", answer: "Is that a cat?" },
    { question: "これ　は　いぬ　です", answer: "This is a dog" },
    { question: "これ　は　わたし　の　いえ　です", answer: "This is my house" },
    { question: "あれ　は　ふじさん　ですか？", answer: "Is that Mt Fuji?" },
    { question: "それ　は　とけい　ですか？", answer: "Is that a clock?" },
    { question: "それ　は　なん　ですか？", answer: "What is that?" },
    { question: "これ　は　何　ですか？", answer: "What is this?" },
    { question: "あれ　は　えき　です", answer: "That is station" },
    { question: "あれ　は　こうえん　じゃありません", answer: "That is not a park" },
    { question: "あれ　は　こうえん　じゃありません", answer: "That is not a park" },
    { question: "これ　は　こうばん　です", answer: "This is police station" },
    { question: "ねこ　は　どうぶつ　です", answer: "The cat is an animal" },
    { question: "はな　は　どうぶつ　ではありません", answer: "The flower is not an animal" },
];