const words = [
    { question: "あそこ", answer: "over there" },
    { question: "あちら", answer: "over there" },
    { question: "あなた", answer: "you" },
    { question: "あに", answer: "older brother" },
    { question: "あね", answer: "older sister" },
    { question: "あの", answer: "that" },
    { question: "いくつ", answer: "how many" },
    { question: "いくら", answer: "how much" },
    { question: "いしゃ", answer: "doctor" },
    { question: "いつ", answer: "when" },
    { question: "うみ", answer: "sea" },
    { question: "えいがかん", answer: "cinema" },
    { question: "おかあさん", answer: "mother" },
    { question: "おくさん", answer: "wife" },
    { question: "おじさん", answer: "uncle" },
    { question: "おじいさん", answer: "grand father" },
    { question: "おとうと", answer: "younger brother" },
    { question: "おとこ", answer: "man" },
    { question: "おとこのこ", answer: "boy" },
    { question: "おとな", answer: "adult" },
    { question: "おにいさん", answer: "elder brother" },
    { question: "おねえさん", answer: "elder sister" },
    { question: "おばさん", answer: "aunt" },
    { question: "おばあさん", answer: "grand mother" },
    { question: "おんな", answer: "woman" },
    { question: "おんなのこ", answer: "girl" },
    { question: "かいしゃ", answer: "company" },
    { question: "かぞく", answer: "family" },
    { question: "かた", answer: "person" },
    { question: "がっこう", answer: "school" },
    { question: "かない", answer: "my wife" },
    { question: "きょうしつ", answer: "class room" },
    { question: "きょうだい", answer: "siblings" },
    { question: "ここ", answer: "here" },
    { question: "ごしゅじん", answer: "husband" },
    { question: "こちら", answer: "here" },
    { question: "この", answer: "this" },
    { question: "さき", answer: "ahead" },
    { question: "〜さん", answer: "Mr Ms" },
    { question: "じぶん", answer: "oneself" },
    { question: "せいと", answer: "student" },
    { question: "せんせい", answer: "teacher" },
    { question: "そこ", answer: "there" },
    { question: "そちら", answer: "there" },
    { question: "その", answer: "that" },
    { question: "だいがく", answer: "university" },
    { question: "だれ", answer: "who" },
    { question: "ちかてつ", answer: "subway" },
    { question: "ちち", answer: "father" },
    { question: "どこ", answer: "where" },
    { question: "としょかん", answer: "library" },
    { question: "どちら", answer: "which" },
    { question: "どなた", answer: "who" },
    { question: "どの", answer: "which" },
    { question: "どれ", answer: "which" },
    { question: "どんな", answer: "what kind of" },
    { question: "なに", answer: "what" },
    { question: "はは", answer: "mother" },
    { question: "ひと", answer: "person" },
    { question: "みせ", answer: "shop" },
    { question: "みち", answer: "road" },
    { question: "みなさん", answer: "everyone" },
    { question: "みんな", answer: "all" },
    { question: "やおや", answer: "vegetable shop" },
    { question: "やま", answer: "mountain" },
    { question: "りゅうがくせい", answer: "foreign student" },
    { question: "りょうしん", answer: "parents" },
];