const words = [
    { message: "Change following adjective word to the NEGATIVE.",question: "いっしょ",meaning:  ["together" ], answer: ["いっしょじゃない","いっしょではない","いっしょじゃありません","いっしょではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "いや",meaning:  ["not likable","unpleasant" ], answer: ["いやだった","いやでした" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "おおぜい",meaning:  ["many people" ], answer: ["おおぜいじゃなかった","おおぜいではなかった","おおぜいじゃありませんでした","おおぜいではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "おなじ",meaning:  ["same" ], answer: ["おなじじゃない","おなじではない","おなじじゃありません","おなじではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "きらい",meaning:  ["dislike" ], answer: ["きらいだった","きらいでした" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "きれい",meaning:  ["beautiful","clean" ], answer: ["きれいじゃなかった","きれいではなかった","きれいじゃありませんでした","きれいではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "げんき",meaning:  ["vigor","health","vitality" ], answer: ["げんきじゃない","げんきではない","げんきじゃありません","げんきではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "しずか",meaning:  ["quiet" ], answer: ["しずかだった","しずかでした" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "じょうず",meaning:  ["good at" ], answer: ["じょうずじゃなかった","じょうずではなかった","じょうずじゃありませんでした","じょうずではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "じょうぶ",meaning:  ["strong","durable" ], answer: ["じょうぶじゃない","じょうぶではない","じょうぶじゃありません","じょうぶではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "だいじょうぶ",meaning:  ["ok","alright" ], answer: ["だいじょうぶだった","だいじょうぶでした" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "だいすき",meaning:  ["love" ], answer: ["だいすきじゃなかった","だいすきではなかった","だいすきじゃありませんでした","だいすきではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "たいせつ",meaning:  ["important" ], answer: ["たいせつじゃない","たいせつではない","たいせつじゃありません","たいせつではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "たいへん",meaning:  ["very","serious" ], answer: ["たいへんだった","たいへんでした" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "にぎやか",meaning:  ["lively" ], answer: ["にぎやかじゃなかった","にぎやかではなかった","にぎやかじゃありませんでした","にぎやかではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "ひま",meaning:  ["free time","leisure","boring" ], answer: ["ひまじゃない","ひまではない","ひまじゃありません","ひまではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "へた",meaning:  ["not good at" ], answer: ["へただった","へたでした" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "べんり",meaning:  ["convenient" ], answer: ["べんりじゃなかった","べんりではなかった","べんりじゃありませんでした","べんりではありませんでした" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "まっすぐ",meaning:  ["straight ahead" ], answer: ["まっすぐじゃない","まっすぐではない","まっすぐじゃありません","まっすぐではありません" ]},
    { message: "Change following adjective word to the PAST.",question: "りっぱ",meaning:  ["splendid" ], answer: ["りっぱだった","りっぱでした" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "あおい",meaning:  ["blue" ], answer: ["あおくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "あかい",meaning:  ["red" ], answer: ["あかくない" ]},
    { message: "Change following adjective word to the PAST.",question: "あかるい",meaning:  ["light","bright" ], answer: ["あかるかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "あたたかい",meaning:  ["warm" ], answer: ["あたたかくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "あたらしい",meaning:  ["new" ], answer: ["あたらしくない" ]},
    { message: "Change following adjective word to the PAST.",question: "あつい",meaning:  ["hot","(air)" ], answer: ["あつかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "あつい",meaning:  ["thick" ], answer: ["あつくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "あぶない",meaning:  ["dangerous" ], answer: ["あぶなくない" ]},
    { message: "Change following adjective word to the PAST.",question: "あまい",meaning:  ["sweet" ], answer: ["あまかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "いい",meaning:  ["good" ], answer: ["いいくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "いそがしい",meaning:  ["busy" ], answer: ["そがしくない" ]},
    { message: "Change following adjective word to the PAST.",question: "いたい",meaning:  ["painful" ], answer: ["たかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "うすい",meaning:  ["thin" ], answer: ["うすくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "おいしい",meaning:  ["tasty","delicious" ], answer: ["おしくない" ]},
    { message: "Change following adjective word to the PAST.",question: "おおきい",meaning:  ["big" ], answer: ["おおきかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "おそい",meaning:  ["late","slow" ], answer: ["おそくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "おもい",meaning:  ["heavy" ], answer: ["おもくない" ]},
    { message: "Change following adjective word to the PAST.",question: "おもしろい",meaning:  ["interesting","funny" ], answer: ["おもしろかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "からい",meaning:  ["hot","spicy" ], answer: ["からくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "かるい",meaning:  ["light","(not heavy)" ], answer: ["かるくない" ]},
    { message: "Change following adjective word to the PAST.",question: "かわいい",meaning:  ["cute","pretty" ], answer: ["かわいかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "きたない",meaning:  ["dirty" ], answer: ["きたなくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "くらい",meaning:  ["dark" ], answer: ["くらくない" ]},
    { message: "Change following adjective word to the PAST.",question: "くろい",meaning:  ["black" ], answer: ["くろかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "さむい",meaning:  ["cold" ], answer: ["さむくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "しろい",meaning:  ["white" ], answer: ["しろくない" ]},
    { message: "Change following adjective word to the PAST.",question: "すずしい",meaning:  ["cool" ], answer: ["すずしかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "せまい",meaning:  ["narrow" ], answer: ["せまくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "たかい",meaning:  ["high","expensive" ], answer: ["たかくない" ]},
    { message: "Change following adjective word to the PAST.",question: "たのしい",meaning:  ["pleasant","enjoyable" ], answer: ["たのしかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "ちいさい",meaning:  ["small" ], answer: ["ちいさくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "ちかい",meaning:  ["near","close" ], answer: ["ちかくない" ]},
    { message: "Change following adjective word to the PAST.",question: "つまらない",meaning:  ["uninteresting" ], answer: ["つまらなかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "つめたい",meaning:  ["cold" ], answer: ["つめたくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "つよい",meaning:  ["strong" ], answer: ["つよくない" ]},
    { message: "Change following adjective word to the PAST.",question: "とおい",meaning:  ["far" ], answer: ["とおかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "ながい",meaning:  ["long" ], answer: ["ながくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "はやい",meaning:  ["fast","quick" ], answer: ["はやくない" ]},
    { message: "Change following adjective word to the PAST.",question: "ひくい",meaning:  [" low" ], answer: ["ひくかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "ひろい",meaning:  ["wide","spacious" ], answer: ["ひろくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "ふとい",meaning:  ["thick","fat" ], answer: ["ふとくない" ]},
    { message: "Change following adjective word to the PAST.",question: "ふるい",meaning:  ["old" ], answer: ["ふるかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "ほしい",meaning:  ["want " ], answer: ["ほしくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "ほそい",meaning:  ["thin","fine" ], answer: ["ほそくない" ]},
    { message: "Change following adjective word to the PAST.",question: "まずい",meaning:  ["bad tasting" ], answer: ["まずかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "まるい",meaning:  ["round" ], answer: ["まるくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "みじかい",meaning:  ["short" ], answer: ["みじかくない" ]},
    { message: "Change following adjective word to the PAST.",question: "むずかしい",meaning:  ["difficult" ], answer: ["むずかしかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "やさしい",meaning:  ["gentle" ], answer: ["やさしくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "やすい",meaning:  ["cheap","inexpensive" ], answer: ["やすくない" ]},
    { message: "Change following adjective word to the PAST.",question: "よい",meaning:  ["good" ], answer: ["よかった" ]},
    { message: "Change following adjective word to the NEGATIVE PAST.",question: "わかい",meaning:  ["young" ], answer: ["わかくなかった" ]},
    { message: "Change following adjective word to the NEGATIVE.",question: "わるい",meaning:  ["bad" ], answer: ["わるくない" ]},    
];

